spring:
  application:
    name: admin-server
  security:
    user:
      name: lili
      password: 123456
server:
  port: 10800
  address: 127.0.0.1
debug: true
management:
    endpoints:
      web:
        exposure:
          include: "*"
logging:
  config: classpath:logback-spring.xml





