spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        pool-name: HikariPool-1
        minimum-idle: 1
        maximum-pool-size: 5
        idle-timeout: 600000
        max-lifetime: 1200000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/db1?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        pool-name: HikariPool-2
        minimum-idle: 1
        maximum-pool-size: 5
        idle-timeout: 600000
        max-lifetime: 1200000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/db2?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    rules:
      readwrite-splitting:
        data-sources:
          ds0:
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave
              load-balancer-name: round_robin
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
    props:
      sql:
        show: true